services:
  - postgresql
addons:
  postgresql: "9.4"
language: java
jdk:
  - oraclejdk8
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ntp
  - sudo service ntp start
before_script:
  - psql -h localhost -c "create user eventsourcing with superuser password 'eventsourcing';" -U postgres 
  - psql -h localhost -c 'create database eventsourcing owner eventsourcing;' -U postgres
script:
  - ./gradlew check
  - ./gradlew publishToMavenLocal
  - cd examples/order && ./gradlew check
after_success:
  - cd ../.. && ./gradlew -Psnapshot=true :eventsourcing-core:bintrayUpload :eventsourcing-layout:bintrayUpload :eventsourcing-hlc:bintrayUpload :eventsourcing-h2:bintrayUpload
env:
  global:
    - secure: "XUgklp7alyLawUShvgVc8ZJ/u6O1kovPO/vQO6VGvq0SxaNO3Ke3AxiNb7GDzNPtrYgDgmnSO7AhXicDkCrVyPvJsSE7G1vbAx6+qMy10tZIYfmgFmrPuzc7sX9Dsa1aDzCcfNP92l/LACjDsWaHAHbs0csHKFele8fqTnDZD4v+6y/MOPKRpK1Gfx1ey0lv7TZI6+1VCRuajL7kSfCHwfZc1XI42VCmuGso8n62ZUyV7rs7kykzjBp3Wg8uksinVaVg4qfOPT0SgHVlfwBiFDR13LtUJrAHaDWyWgafpVyX/BUxlPOnbA66+9SiRz+rO+IkECe2j09lM3gw4K6pFzEWFQG+Xe78nG01iVl/6DZ2BQPlqyYcTCoiqGzj5mZhBcy5fK5ONhLn95zgISrvun+ISaGAioT52i1Xn7pXifq3IxBjVWVVHQux2U/UIe0ICwDMxFtKoV4b5qk7f9V9nvvzojzUL0idvqGBJArWMvfuPoC2z7GVK1InkRhiv5GoP9UjZKWhhy4ZqYFBWpMTTJuGpkdYNjSg40vY9MGTtJg11OQG7HqRAAVSb9c/LJiDo8sPn1EXLLmnN7+KCojLSyRjNeG9hMDsk87M61cEiU9MyIRq//22p66JoitjBK6KL+iVz5SblzUwmPXZzM0oibAfxao3K+UQbZn/d43RQSY="
    - secure: "fa4OGfwXU2Fd6FVBTwqUeuyKlXKEwYx28gOwDnLgCOTjhEOz5NtOG9gedSr8VjHkz7Hi1+5TJd7xRYUUew1ptAWJiURA6ORvloq1XNllxruVHtnuWmop2CfFVi2HMf8mq18zK7JiMhAZP2H8X3XnzWYLC+803AFlt6lmloUZhmQtw60KN/K69Qea5ehBnsm0w20db8a+85kQ7BvCgu7E/fFwvDyWrJUfnJeQ2Ox8QAjdZ+s5GRma59B0zoI302IhSi59H2lJ4whd48o5StJk7hxlTrXsSmweCDdPlkYlb7VofMQzpxRZjbCg+1/ggbrtBVIUFbHKGE78LQbkPwzIP1QJOs1m7FghHeD1KSo3/TNXBYW/NyB3TnFVU411BNsD0gqdxfHe9nSIkEPAGULFNV0hfUd4F4OL9JzAwMVK7ubxlU6l3X9665QreH803RpvyMo4vYzSLNEFU2fi2ytU7uA1mAJ2u2WXHjhUDX0QnOpzg1pEh34LFhOi3NYLy13Wj32BycQW9T+Jamn/2IzsoX9xXBbbtFmoPDzqlNH3drmHSrK+ON9AyU4qPgaeOiCs3DfdeNkXN3qzOCFSBAKiLzKA+JKHJqS1DGWFfIKHpgojhBxBdADvwrcdm9Jcsd6d3UW3dhFatJDrupZpiBGkOC1HTywXsuC7AJfy4o0l/aU="
